"""
Riparr preparer — headless core.

Every security-critical primitive lives here exactly once: Wi-Fi PSK derivation,
SHA-512 crypt, the custom.toml schema, and the removable-disk guards. Both the GUI
(app.py) and the scripted TUI (../flasher/riparr-flash.py) import from this module so
the two can never drift apart on the parts that are dangerous to get wrong.

Stdlib only, except passlib. No AppKit here — this module must stay importable and
testable without a window server.
"""
import hashlib
import json
import os
import re
import secrets
import shutil
import string
import subprocess
import tempfile
import urllib.error
import urllib.parse
import urllib.request

import hostos
import boards

# The official repository. The updater and the image manifest both hang off this.
RIPARR_REPO = "jackharvest/riparr"
GITHUB_API = "https://api.github.com"

# Riparr's port. The *arr family uses doubled digit-pairs -- Radarr 7878, Sonarr 8989,
# Lidarr 8686, Readarr 8787, Prowlarr 9696, Bazarr 6767 -- so Riparr follows suit.
# 9797 is unregistered with IANA (8989 and 6767 are not, which has never troubled the
# family) and collides with none of the ~60 *arr projects in the awesome-arr index.
DEFAULT_PORT = 9797

# Ports a user is likely to already be running. Offered as a warning, never a refusal --
# it is their network and they may well not run the thing we are worried about.
KNOWN_PORTS = {
    80: "a web server", 443: "HTTPS", 22: "SSH", 53: "DNS", 5353: "mDNS (riparr.local)",
    3579: "Ombi", 4545: "Requestrr", 5055: "Overseerr", 5454: "Notifiarr",
    6767: "Bazarr", 6789: "NZBGet", 6969: "Whisparr", 7575: "Homarr", 7777: "Petio",
    7878: "Radarr", 8080: "SABnzbd or qBittorrent", 8096: "Jellyfin or Emby",
    8112: "Deluge", 8181: "Tautulli", 8265: "Tdarr", 8686: "Lidarr", 8787: "Readarr",
    8888: "Unmanic", 8989: "Sonarr", 9091: "Transmission", 9117: "Jackett",
    9696: "Prowlarr", 32400: "Plex",
}


def check_port(port):
    """Returns (ok, message). Only a genuinely unusable port is refused."""
    try:
        port = int(port)
    except (TypeError, ValueError):
        return False, "Enter a number."
    if port < 1024:
        return False, "Ports below 1024 need extra privileges. Pick a higher one."
    if port > 65535:
        return False, "The highest possible port is 65535."
    if port in KNOWN_PORTS:
        return True, "Usually %s. Fine if you don't run it." % KNOWN_PORTS[port]
    return True, ""


def _conf_value(v):
    """One line, no newlines, no trailing space. Everything else is allowed verbatim.

    The reader takes everything after the first `=` to end of line, so there is no
    quoting to agree on -- see packaging/riparr-firstboot.sh. A newline is the only
    character that could break the format, and it cannot legally appear in any of
    these fields anyway.
    """
    return str(v).replace("\r", "").replace("\n", " ").strip()


def build_conf(cfg):
    """Everything the board needs, in one file on the boot partition.

    This is the whole of provisioning now (D25). It used to be eleven files written
    into the image's ext4 root through `debugfs`, because macOS cannot mount ext4 --
    and neither can Windows, which is what made that approach a dead end rather than
    merely awkward. The board reads this and configures itself:
    packaging/riparr-firstboot.sh.

    Read twice on the device, by two different things, which is why the format is
    plain KEY=value: riparr-firstboot.sh parses it at first boot, and riparr.service
    takes RIPARR_PORT from it through `EnvironmentFile=` on every boot after that.

    The Wi-Fi passphrase is never here. `psk` is the PBKDF2-derived key, so the
    passphrase does not touch the card even though this partition is FAT and readable
    by anyone holding it -- and first boot strips the key and the SSH key out of this
    file once they have been applied.
    """
    lines = [
        "# Generated by the Riparr Preparer.",
        "# Read at first boot by riparr-firstboot.sh, and by riparr.service after that.",
        "RIPARR_PORT=%d" % int(cfg.get("port", DEFAULT_PORT)),
        "RIPARR_HOSTNAME=%s" % _conf_value(cfg.get("hostname", "riparr")),
    ]
    # Record which board this card was prepared for. Nothing on the box needs it to boot
    # -- provisioning is the same across Armbian boards -- but it makes a support question
    # answerable ("what hardware is this?") without a guessing game, and gives any future
    # board-specific behaviour something to key off.
    for key, value in (("RIPARR_BOARD", cfg.get("board")),
                       ("RIPARR_COUNTRY", cfg.get("country")),
                       ("RIPARR_TIMEZONE", cfg.get("timezone")),
                       ("RIPARR_WIFI_SSID", cfg.get("ssid")),
                       ("RIPARR_WIFI_PSK", cfg.get("psk") or cfg.get("wifi_psk")),
                       ("RIPARR_SSH_KEY", cfg.get("authorized_key"))):
        if value:
            lines.append("%s=%s" % (key, _conf_value(value)))
    if cfg.get("hidden"):
        lines.append("RIPARR_WIFI_HIDDEN=1")
    return "\n".join(lines) + "\n"


# The Orange Pi Zero 2W has dual-band WiFi 5 (2.4 + 5 GHz), so both are offered.
#
# This was {"2.4"} while the board was believed to be a Raspberry Pi Zero 2 W, whose
# radio genuinely is single-band -- correct then, wrong now. 5 GHz matters here beyond
# convenience: upload rate is the binding constraint in the D11 streaming design, so
# the faster band directly raises how many discs an hour the box can clear.
PI_BANDS = {"2.4", "5"}

# Removable-media guard rails.
#
# There used to be a 70 GB ceiling here, and it was doing a job it should never have
# been given: it was the only thing standing between the user and their photo backup
# drive, because the removability test below it was an *or* -- `Ejectable or
# RemovableMedia` -- which a USB SSD passes on the first term. Size was carrying the
# safety.
#
# It also contradicted our own advice. `docs/design/storage-sizing.md` recommends 128
# or 256 GB for anyone who feeds the box a stack of Blu-rays in an evening, and the
# ceiling made every recommended card invisible. Rufus does not do this: it classifies
# devices and hides the ones that look like hard disks behind a reveal (Alt+F), rather
# than capping capacity. See `classify_disk`.
#
# So the floor stays -- below this nothing can hold the image -- and the ceiling is now
# only a sanity bound on what could conceivably be a card.
MIN_DISK_BYTES = 4_000_000_000
MAX_DISK_BYTES = 2_000_000_000_000

# Fixed overhead written by the image before any staging exists: boot 0.5 GiB + rootfs
# 8.0 GiB (D4). Everything in `card_advice` is derived from what is left after this.
GIB = 1024 ** 3
OVERHEAD_GIB = 8.5

# Commercial disc sizes, real GiB rather than marketed GB
# (docs/design/storage-sizing.md -- "Marketing capacity is a lie").
DVD9_GIB = 7.9
BD50_GIB = 46.6
UHD100_GIB = 93.1


# ───────────────────────────────── Wi-Fi ─────────────────────────────────
#
# The scanning itself lives in hostos/ -- CoreWLAN here, `nmcli` on Linux, `netsh` on
# Windows. What stays is the part that is true regardless of which machine is asking:
# whether the *board's* radio can reach a network, and how a passphrase becomes a PSK.

def pi_can_join(net):
    """Can the board's radio reach this network?

    The Orange Pi Zero 2W is dual-band, so 5 GHz networks are now perfectly reachable
    and are offered. 6 GHz is not -- this is WiFi 5, not 6E. Unknown band is allowed
    through and warned about rather than hidden.
    """
    return (not net["bands"]) or bool(PI_BANDS & set(net["bands"]))


def scan_networks():
    """Returns (networks, method). Never raises; an empty list is a valid answer.

    hostos gathers, this decides: `pi_ok` is a fact about the appliance's radio, not
    about the machine running the Preparer, so it is applied here and applies equally
    on all three platforms.
    """
    try:
        nets, method = hostos.scan_wifi()
    except Exception:
        nets, method = [], "none"
    for n in nets:
        n.setdefault("bands", [])
        n.setdefault("rssi", None)
        n.setdefault("secure", True)
        n["pi_ok"] = pi_can_join(n)
    nets.sort(key=lambda n: (not n["pi_ok"], n["rssi"] is None,
                             -(n["rssi"] or -100), (n.get("ssid") or "").lower()))
    return nets, (method or "none")


def keychain_wifi_password(ssid):
    """The passphrase this machine already knows for a network it has joined.

    A mistyped Wi-Fi password is the most expensive mistake this tool allows: nothing
    detects it, the card writes perfectly, the box boots perfectly and never appears,
    and the only recovery is writing the card again. Meanwhile the correct passphrase
    is, overwhelmingly often, already on the machine running the Preparer.

    Named for the macOS keychain because that is where it started; every platform has
    its own store and hostos knows which. Returns (password, error).
    """
    if not ssid:
        return "", "no network chosen"
    try:
        pw, err = hostos.saved_network_password(ssid)
    except Exception as e:
        return "", str(e)
    return (pw or ""), (err or "")


def derive_psk(ssid, passphrase):
    """WPA-PSK, exactly as wpa_passphrase(8) derives it.

    Doing this here means the plaintext Wi-Fi passphrase never reaches the FAT32
    partition, which is readable by anyone who picks up the card.
    """
    return hashlib.pbkdf2_hmac(
        "sha1", passphrase.encode(), ssid.encode(), 4096, 32).hex()


# ───────────────────────────────── Disks ─────────────────────────────────
#
# The problem this section solves: macOS will happily tell you a device is external,
# physical and ejectable, and that describes both a 32 GB SD card in a reader and a
# 4 TB photo archive. Getting that wrong destroys someone's data.
#
# What the other tools do:
#
#   Rufus classifies rather than caps. `IsHDD()` scores each device from four tables --
#   manufacturer prefixes ("SEAGATE", "WDC" positive; "SANDISK", "LEXAR" negative),
#   keywords ("SSD", "SATA" positive; "Flash", "SD-CARD" negative), and USB VID and
#   VID:PID tables -- combines that with the bus type and the removable-media flag, and
#   files the device as a flash drive, a card reader or a hard disk. Hard disks are
#   *hidden, not excluded*: Alt+F reveals them for the person who really did mean the
#   USB drive. Capacity never removes a device from the list.
#
#   balenaEtcher (drivelist, src/darwin/list.mm) reads DiskArbitration and derives
#   `isSystem = internal && !removable`, `isCard` from the media's IOKit icon being
#   `SD.icns`, and `isUSB`/`isSCSI` from the device protocol. Its own comment records
#   the limit we inherit: since macOS 10.14.3 an external card reader reports
#   `Removable.icns`, and so does an external drive, so the icon cannot separate those
#   two. It then collapses the distinction anyway -- `isRemovable = removable ||
#   ejectable` -- which is exactly the `or` that made the size cap load-bearing here.
#
# So: keep the two flags apart, score the name the way Rufus does, and rank rather than
# exclude. `RemovableMedia` is the SCSI removable-medium bit -- the medium can leave the
# device, which is what a card reader is. `Ejectable` only says the whole device can be
# detached, which every USB disk claims.

# Rufus-style name scoring, in miniature. Positive means hard disk, negative means card
# or flash. Matched against the media name and the IORegistry entry name, upper-cased.
_NAME_SCORES = (
    # Reads as a hard disk or an SSD
    ("SSD", 20), ("HDD", 20), ("SATA", 18), ("NVME", 20), ("SCSI", 15),
    ("MY PASSPORT", 25), ("MY BOOK", 25), ("BACKUP PLUS", 25), ("EXPANSION", 20),
    ("ELEMENTS", 20), ("SEAGATE", 14), ("WDC", 14), ("PORTABLE", 8), ("ARCHIVE", 10),
    ("TIME MACHINE", 25), ("CRUCIAL", 10), ("RUGGED", 15), ("LACIE", 14),
    # Reads as a card or a card reader
    ("SDXC", -30), ("SDHC", -30), ("CARD READER", -30), ("CARDREADER", -30),
    ("MULTI-CARD", -30), ("MULTICARD", -30), ("MMC", -20), ("MICROSD", -30),
    ("SD CARD", -30), ("SD/MMC", -30), ("FLASH", -12), ("STORAGE DEVICE", -6),
    ("MASS STORAGE", -6), ("ULTRA FIT", -12),
)


def _hdd_score(*names):
    """Positive: this reads like a hard disk. Negative: like a card or flash."""
    hay = " ".join(n.upper() for n in names if n)
    score = 0
    for needle, weight in _NAME_SCORES:
        if needle in hay:
            score += weight
    # Bare "SD" as its own word, after the compound forms above have had their say.
    if re.search(r"\bSD\b", hay):
        score -= 15
    return score


# Telling a USB stick apart from a card in a reader.
#
# Both set the removable-medium bit, and Etcher's own source comment records that even
# the IOKit icon cannot separate them. So when the bit is set the *name* decides, and
# when the name says nothing the honest answer is "removable media" rather than a
# guess: calling a Kingston DataTraveler an "SD card" is a confident wrong answer, and
# R5 says that is worse than no answer. All of them are still offered as a target --
# this only decides what the thing is called.
_READER_HINTS = ("CARD READER", "CARDREADER", "MULTI-CARD", "MULTICARD", "CRW",
                 "SDXC", "SDHC", "MICROSD", "SD/MMC", "SD CARD", "MMC", "READER")
_FLASH_HINTS = ("DATATRAVELER", "CRUZER", "ULTRA FIT", "FLASH DRIVE", "FLASH DISK",
                "JUMPDRIVE", "THUMBDRIVE", "STORE N GO", "USB STICK", "BLADE")


def _name_hint(*names):
    hay = " ".join(n.upper() for n in names if n)
    if any(h in hay for h in _READER_HINTS):
        return "reader"
    if any(h in hay for h in _FLASH_HINTS):
        return "flash"
    return ""


# What each platform calls the bus when the medium is a card in a real slot: macOS
# `diskutil`, Windows `MSFT_Disk.BusType`, Linux `lsblk -o TRAN` plus the mmc subsystem.
SD_BUS_PROTOCOLS = {"Secure Digital", "SD", "MMC", "mmc", "sd"}

# kind → (label, is it offered as a card, sort rank)
DISK_KINDS = {
    "sd":       ("SD card", True, 0),
    "reader":   ("SD card", True, 1),
    "flash":    ("USB flash drive", True, 2),
    "removable": ("Removable media", True, 3),
    "disk":     ("External drive", False, 4),
}


def classify_disk(dev, icon=""):
    """What is this thing, and should it be offered as a card? → (kind, why).

    `dev` is the normalised shape hostos returns, so this one function answers the
    question for macOS, Windows and Linux alike. All three expose the same underlying
    signal -- the SCSI removable-medium bit -- under different names, which is exactly
    why the gathering is per-platform and the judgement is not.
    """
    protocol = (dev.get("protocol") or "").strip()
    media_removable = bool(dev.get("removable_media"))
    name = (dev.get("name") or "").strip()
    score = _hdd_score(name, dev.get("model") or "")

    # Strongest signals first, and both mean a real card slot.
    if protocol in SD_BUS_PROTOCOLS:
        return "sd", "in this machine's card slot"
    if icon == "SD.icns":                      # macOS names its own card slots
        return "sd", "recognised by the system as an SD card"

    # A name that shouts hard disk overrides everything below. This is Rufus's
    # `IsHDD` doing its job: a USB enclosure can and does report removable media.
    if score >= 15:
        return "disk", "the name reads as an external drive, not a card"

    # The SCSI removable-medium bit: the medium leaves the device. Card readers set
    # it; USB disk enclosures do not. Etcher throws this away by or-ing it with
    # Ejectable, and that is the distinction the whole list depends on.
    if media_removable:
        hint = _name_hint(name, dev.get("model") or "")
        if hint == "reader":
            return "reader", "removable media in a card reader"
        if hint == "flash":
            return "flash", "a USB flash drive, not a card"
        # The bit only says the medium can leave the device, which is equally true of a
        # card in a reader and of a USB stick. Say that, rather than pick one.
        return "removable", "removable media — a card reader or a USB drive"

    if score <= -10:
        return "flash", "removable USB storage"

    # Ejectable, fixed media, nothing in the name either way. Could be a USB stick,
    # could be an SSD. Say so rather than guess, and keep it out of the card list.
    return "disk", "fixed media — this may be an external drive"


def card_advice(size):
    """What this card buys you, derived rather than tabulated.

    The numbers come from docs/design/storage-sizing.md, and they are all consequences
    of D11: staging is a buffer, not a requirement, so a small card is *slow to feed*,
    never incapable. Nothing here should ever say a disc will not fit.
    """
    staging = size / GIB - OVERHEAD_GIB
    if staging < 4:
        return {"ok": False, "staging_gib": round(max(staging, 0), 1),
                "headline": "Too small",
                "detail": "The system alone needs 8.5 GiB, so this card has no room "
                          "left to stage a rip into."}
    bd = int(staging // BD50_GIB)
    uhd = int(staging // UHD100_GIB)
    dvd = int(staging // DVD9_GIB)

    if bd >= 4:
        head, detail = "Full batch feeding", (
            "Bursts %d Blu-rays or %d UHD discs back to back. Load an evening's stack "
            "and walk away." % (bd, uhd))
    elif bd >= 2:
        head, detail = "A comfortable Blu-ray evening", (
            "Bursts %d Blu-rays back to back, streams UHD. The drive frees up in about "
            "40 minutes a disc instead of three hours." % bd)
    elif bd >= 1:
        head, detail = "Bursts one Blu-ray", (
            "Holds one Blu-ray at full speed and streams UHD. Fine if you feed it a "
            "disc at a time.")
    elif dvd >= 2:
        head, detail = "Streams everything, including UHD", (
            "Every disc still rips — the upload follows the rip rather than waiting "
            "for it. Batch-feeds %d DVDs; Blu-rays go one at a time." % dvd)
    else:
        # Less than one disc of staging. It still rips everything -- that is the whole
        # of D11 -- but nothing is held back, so say that instead of printing
        # "batch-feeds 0 DVDs", which is arithmetic nobody read.
        head, detail = "Small, but it works", (
            "Every disc still rips: the upload follows the rip rather than waiting for "
            "it, so nothing has to fit. One disc at a time, with no room to queue.")

    note = ""
    if size >= 100_000_000_000:
        note = ("At this size, buy high-endurance (SanDisk Max Endurance, Samsung Pro "
                "Endurance) rather than A2 — and not SD Express, which falls back to "
                "legacy speed on this board for 3–4× the price.")
    return {"ok": True, "staging_gib": round(staging, 1), "headline": head,
            "detail": detail, "note": note, "bd50": bd, "uhd": uhd, "dvd9": dvd}


def size_guide():
    """The recommendation table, computed from the same constants as card_advice.

    Written out rather than hard-coded in the interface so the advice on screen cannot
    drift away from the maths in docs/design/storage-sizing.md.
    """
    rows = []
    for gb in (32, 64, 128, 256):
        a = card_advice(gb * 1_000_000_000)
        rows.append({"label": "%d GB" % gb, "bytes": gb * 1_000_000_000,
                     "staging_gib": a["staging_gib"], "headline": a["headline"],
                     "detail": a["detail"]})
    return rows


def list_disks():
    """Candidate devices, classified. The startup disk can never appear.

    hostos returns raw facts; every judgement below is made here, once, so macOS,
    Windows and Linux cannot end up with three different answers to "is that a card".

    Everything that survives is returned -- including things that look like external
    drives, flagged as such. Filtering them out of the *card* list is the interface's
    job (it offers them behind a reveal, the way Rufus does), because a hidden device
    the user is sure they inserted is its own support problem.
    """
    try:
        devices = hostos.list_block_devices()
    except Exception:
        return []
    res = []
    for d in devices:
        if d.get("virtual") or d.get("internal"):
            continue
        # Ejectable *or* removable media decides whether a device is a candidate at
        # all; it is only the card-versus-drive question that needs them apart.
        if not d.get("ejectable") and not d.get("removable_media"):
            continue
        size = d.get("size") or 0
        if not (MIN_DISK_BYTES < size < MAX_DISK_BYTES):
            continue
        kind, why = classify_disk(d, d.get("icon", ""))
        label, is_card, rank = DISK_KINDS[kind]
        res.append({
            "id": d["id"],
            "size": size,
            "size_gb": round(size / 1e9, 1),
            "name": (d.get("name") or "?").strip() or "?",
            "protocol": d.get("protocol", ""),
            "kind": kind,
            "kind_label": label,
            "is_card": is_card,
            "why": why,
            "advice": card_advice(size),
        })
    res.sort(key=lambda d: (DISK_KINDS[d["kind"]][2], d["id"]))
    return res


def validate_disk(ident, allow_any=False):
    """Re-check a disk immediately before writing. Never trust a cached list.

    `allow_any` is the user having deliberately revealed and chosen something we
    classified as an external drive. Without it, a device that changed classification
    between listing and writing -- or an identifier that arrived from somewhere other
    than the list -- is refused.
    """
    for d in list_disks():
        if d["id"] == ident and (allow_any or d["is_card"]):
            return d
    return None


# ──────────────────────────── Provisioning ────────────────────────────

def sha512_crypt(pw):
    """macOS crypt(3) has no $6$ support and silently returns a DES hash instead.

    crypt.crypt('test', '$6$...') yields '$6asQOJRqB1i2' — a DES hash wearing a
    prefix. That produces a card whose console login cannot work, discoverable only
    after flashing and booting. passlib is a hard requirement for this reason.
    """
    from passlib.hash import sha512_crypt as s
    return s.using(rounds=5000).hash(pw)


def _esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def build_toml(cfg):
    """Generate custom.toml.

    Schema verified against raspberrypi-sys-mods/init_config, not from memory.
    `password_encrypted` defaults to TRUE for both [user] and [wlan], so a plaintext
    value supplied without explicitly setting it false fails in a way that is close to
    undiagnosable on a headless box.
    """
    lines = [
        "# Generated by the Riparr Preparer",
        "# Schema verified against raspberrypi-sys-mods/init_config",
        "config_version = 1",
        "",
        "[system]",
        'hostname = "%s"' % _esc(cfg["hostname"]),
        "",
        "[user]",
        'name = "%s"' % _esc(cfg["user"]),
        'password = "%s"' % cfg["pw_hash"],
        "password_encrypted = true",
        "",
        "[ssh]",
        "enabled = true",
        "password_authentication = true",
    ]
    if cfg.get("authorized_key"):
        lines.append('authorized_keys = [ "%s" ]' % _esc(cfg["authorized_key"]))
    lines += ["", "[wlan]", 'ssid = "%s"' % _esc(cfg["ssid"])]
    if cfg.get("secure"):
        lines += ['password = "%s"' % derive_psk(cfg["ssid"], cfg["wifi_pw"]),
                  "password_encrypted = true"]
    lines += ["hidden = %s" % ("true" if cfg.get("hidden") else "false"),
              'country = "%s"' % _esc(cfg.get("country", "US")),
              "",
              "[locale]",
              'keymap = "%s"' % _esc(cfg.get("keymap", "us")),
              'timezone = "%s"' % _esc(cfg.get("timezone", "UTC")),
              ""]
    return "\n".join(lines)


# ─────────────────── what this operating system can do ───────────────────
#
# The Preparer has two halves and they port very differently.
#
# The *setup* half -- find a box on the network, install Riparr on it over SSH, finish
# in a browser -- is stdlib and SSH, and works anywhere Python does.
#
# The *card-writing* half is not portable and pretending otherwise would be the worst
# kind of lie: it would fail at the last step, after the user had entered a Wi-Fi
# password and chosen a disk, with the card possibly half written. writer.py speaks
# `diskutil`, `/dev/rdiskN`, macOS's fskit mount daemon and macOS's rules about which
# application owns removable-media consent. None of that has an equivalent elsewhere
# that has been tested.
#
# So the app says which half it can do, on the first screen, before anything is chosen.
# A Windows or Linux user writes the image with the tool they already have and comes
# back for the setup half, which is the longer and more valuable half anyway.

def host_capabilities():
    import sys
    darwin = sys.platform == "darwin"
    devices = []
    try:
        devices = hostos.list_block_devices()
    except Exception:
        pass
    _, wifi_method = ([], "none")
    try:
        _, wifi_method = hostos.scan_wifi()
    except Exception:
        pass
    return {
        "name": hostos.NAME,
        "platform": sys.platform,
        "write_card": darwin,
        # Everything below works on every platform with a backend, which is why the
        # setup route is offered regardless.
        "list_disks": bool(devices) or darwin,
        "scan_wifi": wifi_method != "none",
        "setup": True,
        "write_note": "" if darwin else (
            "Writing an SD card is macOS-only for now. On %s, write the OS image with "
            "Raspberry Pi Imager or balenaEtcher, put the card in the box, and come "
            "back here to set it up — that is the longer half and it works the same on "
            "every system." % hostos.NAME),
    }


def host_timezone():
    if os.path.islink("/etc/localtime"):
        return os.readlink("/etc/localtime").split("zoneinfo/")[-1]
    return "UTC"


# ────────────────────────────── Assets ──────────────────────────────

def expected_sha256(image_path):
    """Read the checksum sidecar if there is one.

    Raspberry Pi publishes these and we already download them; not checking meant a
    corrupted image produced a card that failed later, mysteriously, on the Pi.
    Format is `<hex>  <filename>`; the filename inside may differ from ours if the
    image was renamed, so only the hex is used.
    """
    for cand in (image_path + ".sha256", os.path.splitext(image_path)[0] + ".sha256"):
        if os.path.exists(cand):
            try:
                first = open(cand).read().split()
                if first and len(first[0]) == 64:
                    return first[0].lower()
            except OSError:
                pass
    return None


def image_kind(path):
    """Whether this image carries Riparr, or is a stock Raspberry Pi OS image.

    The success screen must not promise a web interface that will not be there. Until a
    Riparr image exists, every card written by this tool boots to stock Raspberry Pi OS
    and is reachable only over SSH.
    """
    name = os.path.basename(path).lower()
    return "riparr" if "riparr" in name else "raspios"


def find_images(assets):
    """Every .img.xz in the assets dir, newest first."""
    try:
        names = [f for f in os.listdir(assets) if f.endswith(".img.xz")]
    except OSError:
        return []
    out = []
    for n in names:
        p = os.path.join(assets, n)
        out.append({"name": n, "path": p,
                    "size": os.path.getsize(p),
                    "mtime": os.path.getmtime(p),
                    "sha256": expected_sha256(p),
                    "kind": image_kind(p)})
    out.sort(key=lambda d: d["mtime"], reverse=True)
    return out


# ───────────────────────── OS images, by board ─────────────────────────
#
# The hardware dropdown picks a board; this fetches the right OS image for it. Provisioning
# does not need to know which board it is -- writer.py branches on the *written card's*
# partition layout, not on a board id -- so choosing the board is really choosing the image.


def _parse_sha_file(text):
    """Pull the 64-hex digest out of a `<hex>  <filename>` checksum file."""
    for tok in (text or "").split():
        t = tok.strip().lower()
        if len(t) == 64 and all(c in "0123456789abcdef" for c in t):
            return t
    return None


def _filename_from_headers(resp, fallback):
    """The real image filename, from the Content-Disposition of the resolved download.

    Armbian's durable URL is a redirect whose target names the versioned file; using that
    name means a re-download is recognised as the same image rather than piling up.
    """
    cd = resp.headers.get("Content-Disposition", "") if resp.headers else ""
    m = re.search(r'filename\*?=(?:UTF-8\'\')?"?([^\";]+)', cd)
    if m:
        return os.path.basename(m.group(1).strip())
    # Or the last path segment of the URL we were actually redirected to.
    tail = os.path.basename(urllib.parse.urlparse(resp.geturl()).path)
    return tail if tail.endswith(".img.xz") else fallback


def image_for_board(assets, board_id):
    """A already-downloaded image for this board, or None.

    Matches on the board name embedded in Armbian/Raspberry Pi filenames (e.g.
    `..._Orangepizero2w_...`, `...-raspios-...`), so a folder holding several boards'
    images hands back the right one.
    """
    b = boards.get(board_id)
    if not b:
        return None
    if b["os"] == "raspios":
        needles = ["raspios"]
    else:
        needles = [b["armbian_slug"].replace("-", ""), b["id"].replace("-", "")]
    for img in find_images(assets):
        stem = img["name"].lower().replace("-", "").replace("_", "")
        if any(n in stem for n in needles):
            return img
    return None


def download_image(board_id, assets, progress=None, timeout=60):
    """Fetch a board's OS image into the assets dir and verify it against its checksum.

    Returns {"ok": True, "path", "name", "sha256"} or {"ok": False, "error"}. Never
    raises -- a machine with no internet must fail with a sentence, not a traceback.

    `progress(done_bytes, total_bytes)` is called as the download streams. The checksum
    is fetched first (it is tiny and its absence is a reason not to bother downloading a
    gigabyte), the image is streamed to a temp file, verified, then moved into place with
    a `.sha256` sidecar so the existing write-time verify (writer.py --sha256) covers it
    too. An image already present and matching is returned without re-downloading.
    """
    src = boards.image_source(board_id)
    if not src:
        return {"ok": False, "error": "Unknown board: %s" % board_id}

    existing = image_for_board(assets, board_id)
    if existing and existing.get("sha256"):
        return {"ok": True, "path": existing["path"], "name": existing["name"],
                "sha256": existing["sha256"], "cached": True}

    # 1. The expected checksum. No checksum, no download -- guessing is how a corrupt
    #    image becomes a card that fails later, mysteriously, on the board.
    try:
        req = urllib.request.Request(src["sha_url"], headers={"User-Agent": "riparr-preparer"})
        with urllib.request.urlopen(req, timeout=timeout) as r:
            expected = _parse_sha_file(r.read().decode("utf-8", "ignore"))
    except Exception as e:
        return {"ok": False,
                "error": "Couldn't fetch the image checksum for this board: %s" % e}
    if not expected:
        return {"ok": False,
                "error": "The image checksum for this board could not be read."}

    # 2. Stream the image to a temp file, hashing as it lands.
    os.makedirs(assets, exist_ok=True)
    fd, tmp = tempfile.mkstemp(suffix=".img.xz.part", dir=assets)
    os.close(fd)
    h = hashlib.sha256()
    try:
        req = urllib.request.Request(src["url"], headers={"User-Agent": "riparr-preparer"})
        with urllib.request.urlopen(req, timeout=timeout) as r:
            name = _filename_from_headers(r, "%s.img.xz" % board_id)
            total = int(r.headers.get("Content-Length") or 0)
            done = 0
            with open(tmp, "wb") as f:
                while True:
                    chunk = r.read(1 << 20)
                    if not chunk:
                        break
                    f.write(chunk)
                    h.update(chunk)
                    done += len(chunk)
                    if progress:
                        progress(done, total)
    except Exception as e:
        _rm(tmp)
        return {"ok": False, "error": "The image download failed: %s" % e}

    got = h.hexdigest()
    if got != expected:
        _rm(tmp)
        return {"ok": False,
                "error": "The downloaded image did not match its published checksum. "
                         "Nothing was kept.",
                "detail": "expected %s\ngot      %s" % (expected[:32], got[:32])}

    # 3. Move into place under its real name, with the .sha256 sidecar find_images reads.
    dest = os.path.join(assets, name)
    try:
        _rm(dest)
        os.replace(tmp, dest)
        with open(dest + ".sha256", "w") as f:
            f.write("%s  %s\n" % (expected, name))
    except OSError as e:
        _rm(tmp)
        return {"ok": False, "error": "Could not save the image: %s" % e}
    return {"ok": True, "path": dest, "name": name, "sha256": expected}


def _rm(path):
    try:
        os.unlink(path)
    except OSError:
        pass


# ─────────────────────── External tools we shell out to ───────────────────────
#
# One of them does not ship with macOS and is not on a stock PATH:
#
#   debugfs   e2fsprogs, Homebrew only, and keg-only so it is not linked onto PATH.
#             Needed only for single-partition ext4 images -- Armbian, which is what
#             this project actually writes -- because macOS cannot mount ext4.
#
# `xz` used to be here too. It is gone: both uses moved to the stdlib `lzma` module,
# which links the same liblzma macOS already ships inside libarchive. That was optional
# while this was a Mac tool and became mandatory the moment Windows entered scope --
# see docs/design/cross-platform.md.
#
# debugfs worked for a year purely because the app is launched from a shell and inherits
# a developer's PATH. `launchctl getenv PATH` is empty, so a Finder-launched .app gets
# the launchd default -- /usr/bin:/bin:/usr/sbin:/sbin -- and it disappears. That is the
# very next thing on the backlog (scenario A1), so resolve by absolute path.

def find_tool(name, candidates):
    """Absolute path first, PATH second. PATH is not there under launchd."""
    for p in candidates:
        if os.path.exists(p) and os.access(p, os.X_OK):
            return p
    return shutil.which(name)


def image_layout(path):
    """Does this image need debugfs? Read its MBR without expanding it.

    Decompresses the first sector with the *stdlib* lzma module rather than xz(1),
    which is the point: this has to work on a machine that does not have xz, because
    the whole reason we are here is to tell that person so.
    """
    try:
        import lzma
        with lzma.open(path, "rb") as f:
            mbr = f.read(512)
    except Exception:
        return "unknown"
    if len(mbr) < 512:
        return "unknown"
    types = [mbr[0x1BE + 16 * i + 4] for i in range(4)]
    first = next((t for t in types if t), 0)
    if first in (0x0b, 0x0c):
        return "fat-boot"            # Raspberry Pi style: provisioned by copying a file
    if first == 0x83:
        return "ext4-root"           # Armbian style: provisioned through debugfs
    return "unknown"


def missing_tools(image=None):
    """Everything this write will shell out to that is not installed.

    Checked *before* the authorization dialog. Discovering a missing tool afterwards
    means the user has already typed an admin password and the card has already been
    unmounted, and the failure arrives as "The write stopped unexpectedly" with an
    errno -- which names neither the cause nor the fix.
    """
    out = []
    # Only ask for debugfs when the image actually needs it. Warning about a tool this
    # particular write will never run is its own kind of wrong.
    if image and image_layout(image) in ("ext4-root", "unknown"):
        try:
            import armbian
            have = armbian.find_debugfs()
        except Exception:
            have = None
        if not have:
            out.append({
                "tool": "debugfs",
                "why": "needed to write settings into the card's Linux partition, "
                       "which macOS cannot mount",
                "fix": "brew install e2fsprogs",
            })
    return out


def _xz_varint(buf, pos):
    """The .xz multibyte integer: 7 bits per byte, high bit continues. (value, pos)."""
    value, shift = 0, 0
    while True:
        if pos >= len(buf) or shift > 63:
            raise ValueError("bad multibyte integer")
        b = buf[pos]
        pos += 1
        value |= (b & 0x7F) << shift
        if not (b & 0x80):
            return value, pos
        shift += 7


def uncompressed_size(path):
    """Read the real expanded size out of the xz index, for an honest progress bar.

    Parses the container rather than shelling out to `xz --robot --list`. xz(1) is
    Homebrew-only on macOS and absent on Windows, and this is a fixed, documented
    layout: the last 12 bytes are the stream footer, whose Backward Size field says how
    far back the index starts, and the index carries one uncompressed size per block.

    Reading the footer means this stays O(1) rather than decompressing 1.4 GiB to find
    out how big it is. Cross-checked against `xz --robot --list` on the real image.
    """
    try:
        size = os.path.getsize(path)
        with open(path, "rb") as f:
            f.seek(-12, os.SEEK_END)
            footer = f.read(12)
            if footer[10:12] != b"YZ":
                return 0
            backward = (int.from_bytes(footer[4:8], "little") + 1) * 4
            index_at = size - 12 - backward
            if index_at < 0:
                return 0
            f.seek(index_at)
            index = f.read(backward)

        if not index or index[0] != 0x00:      # Index Indicator
            return 0
        count, pos = _xz_varint(index, 1)
        total = 0
        for _ in range(count):
            _unpadded, pos = _xz_varint(index, pos)     # compressed, not wanted
            uncompressed, pos = _xz_varint(index, pos)
            total += uncompressed
        return total
    except Exception:
        return 0


def ensure_password(assets):
    """Read the saved account password, generating one on first run."""
    pwfile = os.path.join(assets, "user_password.txt")
    if os.path.exists(pwfile):
        return open(pwfile).read().strip(), False
    pw = "".join(secrets.choice(string.ascii_letters + string.digits)
                 for _ in range(20))
    with open(pwfile, "w") as f:
        f.write(pw + "\n")
    os.chmod(pwfile, 0o600)
    return pw, True


def public_key(assets):
    p = os.path.join(assets, "riparr_key.pub")
    return open(p).read().strip() if os.path.exists(p) else None


def ensure_key(assets):
    """Return the public half of the box's SSH key, generating the pair on first run.

    The passwordless-SSH setup path depends on a key at `<assets>/riparr_key`, and until
    now nothing created it -- the code and the guides both assumed the user had made one,
    so `start_setup` simply failed with "the SSH key is missing" on a fresh build folder.
    Generate it here instead, the same way `ensure_password` handles the account
    password: create it once, keep it, reuse it.

    ed25519, no passphrase (this is an unattended appliance key), and the private half is
    written 0600 -- ssh-keygen does that itself, but it is asserted here so a future
    change cannot quietly loosen it. A per-build key means one compromised build folder
    cannot reach anyone else's box.

    Returns the public key string, or None if ssh-keygen is not on this host (Windows
    without the OpenSSH client). The caller degrades to password SSH, exactly as it did
    when the key was simply absent.
    """
    priv = os.path.join(assets, "riparr_key")
    pub = priv + ".pub"
    if os.path.exists(pub):
        return open(pub).read().strip()

    keygen = shutil.which("ssh-keygen")
    if not keygen:
        return None
    # A stale private key with no public half would make ssh-keygen refuse; clear it.
    if os.path.exists(priv):
        os.remove(priv)
    r = subprocess.run(
        [keygen, "-t", "ed25519", "-N", "", "-C", "riparr", "-f", priv],
        capture_output=True, text=True)
    if r.returncode != 0 or not os.path.exists(pub):
        return None
    try:
        os.chmod(priv, 0o600)
    except OSError:
        pass
    return open(pub).read().strip()


# ────────────────────────────── Updates ──────────────────────────────

def check_for_update(current_version, repo=RIPARR_REPO, timeout=6):
    """Ask GitHub for the newest release.

    Returns a dict the UI can render directly. Never raises — a machine with no
    internet must still be able to flash a card.
    """
    url = "%s/repos/%s/releases/latest" % (GITHUB_API, repo)
    req = urllib.request.Request(url, headers={
        "Accept": "application/vnd.github+json",
        "User-Agent": "riparr-preparer/%s" % current_version,
    })
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            data = json.load(r)
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return {"status": "no-releases", "repo": repo}
        return {"status": "error", "detail": "HTTP %s" % e.code}
    except Exception as e:
        return {"status": "offline", "detail": str(e)}

    tag = (data.get("tag_name") or "").lstrip("v")
    assets = [{"name": a.get("name"), "url": a.get("browser_download_url"),
               "size": a.get("size")} for a in data.get("assets", [])]
    return {
        "status": "update" if _newer(tag, current_version) else "current",
        "version": tag,
        "current": current_version,
        "url": data.get("html_url"),
        "notes": data.get("body") or "",
        "published": data.get("published_at"),
        "assets": assets,
        "repo": repo,
    }


def _newer(a, b):
    """Compare dotted versions. Non-numeric segments sort as 0 rather than crashing."""
    def parts(v):
        return [int(x) if x.isdigit() else 0
                for x in re.split(r"[.\-+]", v or "") if x != ""]
    pa, pb = parts(a), parts(b)
    n = max(len(pa), len(pb))
    pa += [0] * (n - len(pa))
    pb += [0] * (n - len(pb))
    return pa > pb
