"""
Riparr preparer — headless core.

Every security-critical primitive lives here exactly once: Wi-Fi PSK derivation,
SHA-512 crypt, the custom.toml schema, and the removable-disk guards. Both the GUI
(app.py) and the scripted TUI (../flasher/riparr-flash.py) import from this module so
the two can never drift apart on the parts that are dangerous to get wrong.

Stdlib only, except passlib. No AppKit here — this module must stay importable and
testable without a window server.
"""
import hashlib
import json
import os
import plistlib
import re
import secrets
import string
import subprocess
import urllib.error
import urllib.request

# The official repository. The updater and the image manifest both hang off this.
RIPARR_REPO = "jackharvest/riparr"
GITHUB_API = "https://api.github.com"

# Riparr's port. The *arr family uses doubled digit-pairs -- Radarr 7878, Sonarr 8989,
# Lidarr 8686, Readarr 8787, Prowlarr 9696, Bazarr 6767 -- so Riparr follows suit.
# 9797 is unregistered with IANA (8989 and 6767 are not, which has never troubled the
# family) and collides with none of the ~60 *arr projects in the awesome-arr index.
DEFAULT_PORT = 9797

# Ports a user is likely to already be running. Offered as a warning, never a refusal --
# it is their network and they may well not run the thing we are worried about.
KNOWN_PORTS = {
    80: "a web server", 443: "HTTPS", 22: "SSH", 53: "DNS", 5353: "mDNS (riparr.local)",
    3579: "Ombi", 4545: "Requestrr", 5055: "Overseerr", 5454: "Notifiarr",
    6767: "Bazarr", 6789: "NZBGet", 6969: "Whisparr", 7575: "Homarr", 7777: "Petio",
    7878: "Radarr", 8080: "SABnzbd or qBittorrent", 8096: "Jellyfin or Emby",
    8112: "Deluge", 8181: "Tautulli", 8265: "Tdarr", 8686: "Lidarr", 8787: "Readarr",
    8888: "Unmanic", 8989: "Sonarr", 9091: "Transmission", 9117: "Jackett",
    9696: "Prowlarr", 32400: "Plex",
}


def check_port(port):
    """Returns (ok, message). Only a genuinely unusable port is refused."""
    try:
        port = int(port)
    except (TypeError, ValueError):
        return False, "Enter a number."
    if port < 1024:
        return False, "Ports below 1024 need extra privileges. Pick a higher one."
    if port > 65535:
        return False, "The highest possible port is 65535."
    if port in KNOWN_PORTS:
        return True, "Usually %s. Fine if you don't run it." % KNOWN_PORTS[port]
    return True, ""


def build_conf(cfg):
    """Settings the Riparr installer reads off the boot partition.

    custom.toml has a fixed schema owned by Raspberry Pi OS, so anything of ours lives
    in its own file alongside it.
    """
    return (
        "# Generated by the Riparr Preparer. Read by tools/install.sh on the device.\n"
        "RIPARR_PORT=%d\n"
        "RIPARR_HOSTNAME=%s\n" % (int(cfg.get("port", DEFAULT_PORT)),
                                   cfg.get("hostname", "riparr")))


# The Orange Pi Zero 2W has dual-band WiFi 5 (2.4 + 5 GHz), so both are offered.
#
# This was {"2.4"} while the board was believed to be a Raspberry Pi Zero 2 W, whose
# radio genuinely is single-band -- correct then, wrong now. 5 GHz matters here beyond
# convenience: upload rate is the binding constraint in the D11 streaming design, so
# the faster band directly raises how many discs an hour the box can clear.
PI_BANDS = {"2.4", "5"}

# Removable-media guard rails.
#
# There used to be a 70 GB ceiling here, and it was doing a job it should never have
# been given: it was the only thing standing between the user and their photo backup
# drive, because the removability test below it was an *or* -- `Ejectable or
# RemovableMedia` -- which a USB SSD passes on the first term. Size was carrying the
# safety.
#
# It also contradicted our own advice. `docs/design/storage-sizing.md` recommends 128
# or 256 GB for anyone who feeds the box a stack of Blu-rays in an evening, and the
# ceiling made every recommended card invisible. Rufus does not do this: it classifies
# devices and hides the ones that look like hard disks behind a reveal (Alt+F), rather
# than capping capacity. See `classify_disk`.
#
# So the floor stays -- below this nothing can hold the image -- and the ceiling is now
# only a sanity bound on what could conceivably be a card.
MIN_DISK_BYTES = 4_000_000_000
MAX_DISK_BYTES = 2_000_000_000_000

# Fixed overhead written by the image before any staging exists: boot 0.5 GiB + rootfs
# 8.0 GiB (D4). Everything in `card_advice` is derived from what is left after this.
GIB = 1024 ** 3
OVERHEAD_GIB = 8.5

# Commercial disc sizes, real GiB rather than marketed GB
# (docs/design/storage-sizing.md -- "Marketing capacity is a lie").
DVD9_GIB = 7.9
BD50_GIB = 46.6
UHD100_GIB = 93.1


# ───────────────────────────────── Wi-Fi ─────────────────────────────────

def _band_for_channel(ch_band):
    return {1: "2.4", 2: "5", 3: "6"}.get(ch_band)


def scan_corewlan():
    """Live scan via CoreWLAN: SSID, band, RSSI, security.

    This is the only scan method that returns unredacted SSIDs without a Location
    Services grant. `airport` was removed in macOS 26 and `system_profiler` redacts.
    """
    import CoreWLAN
    iface = CoreWLAN.CWWiFiClient.sharedWiFiClient().interface()
    if iface is None:
        return {}
    nets, _ = iface.scanForNetworksWithSSID_error_(None, None)
    agg = {}
    for n in nets or []:
        ssid = n.ssid()
        if not ssid:
            continue
        ch = n.wlanChannel()
        band = _band_for_channel(ch.channelBand() if ch else 0)
        try:
            secure = not n.supportsSecurity_(0)  # kCWSecurityNone
        except Exception:
            secure = True
        rssi = n.rssiValue()
        e = agg.get(ssid)
        if e is None:
            agg[ssid] = {
                "ssid": ssid,
                "bands": [band] if band else [],
                "rssi": rssi,
                "secure": secure,
                "saved": False,
                "seen": True,
            }
        else:
            if band and band not in e["bands"]:
                e["bands"].append(band)
            if rssi is not None and (e["rssi"] is None or rssi > e["rssi"]):
                e["rssi"] = rssi
    return agg


def scan_system_profiler():
    """Fallback scan. SSIDs come back '<redacted>' without Location Services."""
    try:
        out = subprocess.run(
            ["system_profiler", "SPAirPortDataType"],
            capture_output=True, text=True, timeout=45).stdout
    except Exception:
        return {}
    agg, cur = {}, None
    for line in out.splitlines():
        m = re.match(r"^\s{12}([^\s:][^:]*):\s*$", line)
        if m:
            cur = m.group(1).strip()
            if cur.startswith("<"):
                cur = None
            elif cur not in agg:
                agg[cur] = {"ssid": cur, "bands": [], "rssi": None,
                            "secure": True, "saved": False, "seen": True}
            continue
        if cur and "Channel:" in line:
            b = re.search(r"\((2|5|6)GHz", line)
            if b:
                band = {"2": "2.4", "5": "5", "6": "6"}[b.group(1)]
                if band not in agg[cur]["bands"]:
                    agg[cur]["bands"].append(band)
        if cur and "Security:" in line and "None" in line:
            agg[cur]["secure"] = False
    return agg


def wifi_device():
    """The Wi-Fi interface's BSD name. Not always en0.

    On a Mac with Thunderbolt Ethernet, or any machine where the ports enumerate
    differently, en0 is the wired interface and the Wi-Fi questions asked of it come
    back empty -- which reads as "you have no saved networks" rather than "we asked the
    wrong device".
    """
    try:
        out = subprocess.run(["networksetup", "-listallhardwareports"],
                             capture_output=True, text=True, timeout=15).stdout
        block = None
        for line in out.splitlines():
            line = line.strip()
            if line.startswith("Hardware Port:"):
                block = line.split(":", 1)[1].strip()
            elif line.startswith("Device:") and block in ("Wi-Fi", "AirPort"):
                return line.split(":", 1)[1].strip()
    except Exception:
        pass
    return "en0"


def saved_networks():
    """Preferred networks, unredacted, but with no band or signal information."""
    try:
        out = subprocess.run(
            ["networksetup", "-listpreferredwirelessnetworks", wifi_device()],
            capture_output=True, text=True, timeout=15).stdout
        return [l.strip() for l in out.splitlines()[1:] if l.strip()]
    except Exception:
        return []


def keychain_wifi_password(ssid):
    """The Wi-Fi passphrase this Mac already knows, from the login keychain.

    A mistyped Wi-Fi password is the single most expensive mistake available in this
    tool: nothing detects it, the card writes perfectly, the box boots perfectly, and
    it never appears on the network -- and the only recovery is to write the card
    again. Meanwhile the correct passphrase is, in the overwhelmingly common case,
    sitting in the keychain of the machine running the Preparer.

    macOS shows its own authorization dialog the first time. That prompt is a feature:
    it is the OS asking on the user's behalf, in a dialog they recognise, and no
    passphrase is read without their consent. Returns (password, error).
    """
    if not ssid:
        return "", "no network chosen"
    try:
        p = subprocess.run(
            ["security", "find-generic-password",
             "-D", "AirPort network password", "-a", ssid, "-w"],
            capture_output=True, text=True, timeout=60)
    except Exception as e:
        return "", str(e)
    if p.returncode == 0:
        return p.stdout.rstrip("\n"), ""
    err = (p.stderr or "").strip()
    if "could not be found" in err or p.returncode == 44:
        return "", "This Mac hasn't saved a password for that network."
    if "User canceled" in err or "-128" in err:
        return "", "Cancelled."
    return "", err or "The keychain wouldn't give it up."


def pi_can_join(net):
    """Can the board's radio reach this network?

    The Orange Pi Zero 2W is dual-band, so 5 GHz networks are now perfectly reachable
    and are offered. 6 GHz is not -- this is WiFi 5, not 6E. Unknown band is allowed
    through and warned about rather than hidden.
    """
    return (not net["bands"]) or bool(PI_BANDS & set(net["bands"]))


def scan_networks():
    """Returns (networks, method). Degrades gracefully; never raises."""
    agg, method = {}, None
    try:
        agg = scan_corewlan()
        if agg:
            method = "live"
    except Exception:
        agg = {}
    if not agg:
        agg = scan_system_profiler()
        if agg:
            method = "system_profiler"
    for s in saved_networks():
        if s in agg:
            agg[s]["saved"] = True
        else:
            agg[s] = {"ssid": s, "bands": [], "rssi": None, "secure": True,
                      "saved": True, "seen": False}
    if agg and not method:
        method = "saved"
    nets = list(agg.values())
    for n in nets:
        n["pi_ok"] = pi_can_join(n)
    nets.sort(key=lambda n: (not n["pi_ok"], n["rssi"] is None,
                             -(n["rssi"] or -100), n["ssid"].lower()))
    return nets, (method or "none")


def derive_psk(ssid, passphrase):
    """WPA-PSK, exactly as wpa_passphrase(8) derives it.

    Doing this here means the plaintext Wi-Fi passphrase never reaches the FAT32
    partition, which is readable by anyone who picks up the card.
    """
    return hashlib.pbkdf2_hmac(
        "sha1", passphrase.encode(), ssid.encode(), 4096, 32).hex()


# ───────────────────────────────── Disks ─────────────────────────────────
#
# The problem this section solves: macOS will happily tell you a device is external,
# physical and ejectable, and that describes both a 32 GB SD card in a reader and a
# 4 TB photo archive. Getting that wrong destroys someone's data.
#
# What the other tools do:
#
#   Rufus classifies rather than caps. `IsHDD()` scores each device from four tables --
#   manufacturer prefixes ("SEAGATE", "WDC" positive; "SANDISK", "LEXAR" negative),
#   keywords ("SSD", "SATA" positive; "Flash", "SD-CARD" negative), and USB VID and
#   VID:PID tables -- combines that with the bus type and the removable-media flag, and
#   files the device as a flash drive, a card reader or a hard disk. Hard disks are
#   *hidden, not excluded*: Alt+F reveals them for the person who really did mean the
#   USB drive. Capacity never removes a device from the list.
#
#   balenaEtcher (drivelist, src/darwin/list.mm) reads DiskArbitration and derives
#   `isSystem = internal && !removable`, `isCard` from the media's IOKit icon being
#   `SD.icns`, and `isUSB`/`isSCSI` from the device protocol. Its own comment records
#   the limit we inherit: since macOS 10.14.3 an external card reader reports
#   `Removable.icns`, and so does an external drive, so the icon cannot separate those
#   two. It then collapses the distinction anyway -- `isRemovable = removable ||
#   ejectable` -- which is exactly the `or` that made the size cap load-bearing here.
#
# So: keep the two flags apart, score the name the way Rufus does, and rank rather than
# exclude. `RemovableMedia` is the SCSI removable-medium bit -- the medium can leave the
# device, which is what a card reader is. `Ejectable` only says the whole device can be
# detached, which every USB disk claims.

# Rufus-style name scoring, in miniature. Positive means hard disk, negative means card
# or flash. Matched against the media name and the IORegistry entry name, upper-cased.
_NAME_SCORES = (
    # Reads as a hard disk or an SSD
    ("SSD", 20), ("HDD", 20), ("SATA", 18), ("NVME", 20), ("SCSI", 15),
    ("MY PASSPORT", 25), ("MY BOOK", 25), ("BACKUP PLUS", 25), ("EXPANSION", 20),
    ("ELEMENTS", 20), ("SEAGATE", 14), ("WDC", 14), ("PORTABLE", 8), ("ARCHIVE", 10),
    ("TIME MACHINE", 25), ("CRUCIAL", 10), ("RUGGED", 15), ("LACIE", 14),
    # Reads as a card or a card reader
    ("SDXC", -30), ("SDHC", -30), ("CARD READER", -30), ("CARDREADER", -30),
    ("MULTI-CARD", -30), ("MULTICARD", -30), ("MMC", -20), ("MICROSD", -30),
    ("SD CARD", -30), ("SD/MMC", -30), ("FLASH", -12), ("STORAGE DEVICE", -6),
    ("MASS STORAGE", -6), ("ULTRA FIT", -12),
)


def _hdd_score(*names):
    """Positive: this reads like a hard disk. Negative: like a card or flash."""
    hay = " ".join(n.upper() for n in names if n)
    score = 0
    for needle, weight in _NAME_SCORES:
        if needle in hay:
            score += weight
    # Bare "SD" as its own word, after the compound forms above have had their say.
    if re.search(r"\bSD\b", hay):
        score -= 15
    return score


def _media_icons():
    """{bsd name: IOKit icon resource} -- the signal drivelist calls `isCard`.

    `SD.icns` means the media is in a real card slot. Read from `ioreg` so this needs
    no DiskArbitration binding: pyobjc-framework-DiskArbitration is not a dependency
    and should not become one for a single dictionary lookup.
    """
    try:
        out = subprocess.run(["ioreg", "-a", "-c", "IOMedia", "-r", "-l"],
                             capture_output=True).stdout
        root = plistlib.loads(out)
    except Exception:
        return {}
    icons, stack = {}, [root]
    while stack:
        node = stack.pop()
        if isinstance(node, list):
            stack.extend(node)
            continue
        if not isinstance(node, dict):
            continue
        bsd, icon = node.get("BSD Name"), node.get("IOMediaIcon")
        if bsd and isinstance(icon, dict):
            icons[bsd] = icon.get("IOBundleResourceFile", "")
        stack.extend(node.get("IORegistryEntryChildren") or [])
    return icons


def _truthy_removable(value):
    """`RemovableMedia` is a bool on current macOS and a string on older ones."""
    if isinstance(value, str):
        return value.strip().lower() == "removable"
    return bool(value)


# kind → (label, is it offered as a card, sort rank)
DISK_KINDS = {
    "sd":       ("SD card", True, 0),
    "reader":   ("SD card", True, 1),
    "flash":    ("USB flash drive", True, 2),
    "disk":     ("External drive", False, 3),
}


def classify_disk(info, icon=""):
    """What is this thing, and should it be offered as a card? → (kind, why)."""
    protocol = (info.get("BusProtocol") or "").strip()
    media_removable = _truthy_removable(info.get("RemovableMedia"))
    name = (info.get("MediaName") or "").strip()
    score = _hdd_score(name, info.get("IORegistryEntryName") or "")

    # Strongest signals first, and both mean a real card slot.
    if protocol == "Secure Digital":
        return "sd", "in this Mac's card slot"
    if icon == "SD.icns":
        return "sd", "recognised by macOS as an SD card"

    # A name that shouts hard disk overrides everything below. This is Rufus's
    # `IsHDD` doing its job: a USB enclosure can and does report removable media.
    if score >= 15:
        return "disk", "the name reads as an external drive, not a card"

    # The SCSI removable-medium bit: the medium leaves the device. Card readers set
    # it; USB disk enclosures do not. Etcher throws this away by or-ing it with
    # Ejectable, and that is the distinction the whole list depends on.
    if media_removable:
        if score <= -10:
            return "reader", "removable media in a card reader"
        return "reader", "removable media — this is a card in a reader"

    if score <= -10:
        return "flash", "removable USB storage"

    # Ejectable, fixed media, nothing in the name either way. Could be a USB stick,
    # could be an SSD. Say so rather than guess, and keep it out of the card list.
    return "disk", "fixed media — this may be an external drive"


def card_advice(size):
    """What this card buys you, derived rather than tabulated.

    The numbers come from docs/design/storage-sizing.md, and they are all consequences
    of D11: staging is a buffer, not a requirement, so a small card is *slow to feed*,
    never incapable. Nothing here should ever say a disc will not fit.
    """
    staging = size / GIB - OVERHEAD_GIB
    if staging < 4:
        return {"ok": False, "staging_gib": round(max(staging, 0), 1),
                "headline": "Too small",
                "detail": "The system alone needs 8.5 GiB, so this card has no room "
                          "left to stage a rip into."}
    bd = int(staging // BD50_GIB)
    uhd = int(staging // UHD100_GIB)
    dvd = int(staging // DVD9_GIB)

    if bd >= 4:
        head, detail = "Full batch feeding", (
            "Bursts %d Blu-rays or %d UHD discs back to back. Load an evening's stack "
            "and walk away." % (bd, uhd))
    elif bd >= 2:
        head, detail = "A comfortable Blu-ray evening", (
            "Bursts %d Blu-rays back to back, streams UHD. The drive frees up in about "
            "40 minutes a disc instead of three hours." % bd)
    elif bd >= 1:
        head, detail = "Bursts one Blu-ray", (
            "Holds one Blu-ray at full speed and streams UHD. Fine if you feed it a "
            "disc at a time.")
    else:
        head, detail = "Streams everything, including UHD", (
            "Every disc still rips — the upload follows the rip rather than waiting "
            "for it. Batch-feeds %d DVDs; Blu-rays go one at a time." % dvd)

    note = ""
    if size >= 100_000_000_000:
        note = ("At this size, buy high-endurance (SanDisk Max Endurance, Samsung Pro "
                "Endurance) rather than A2 — and not SD Express, which falls back to "
                "legacy speed on this board for 3–4× the price.")
    return {"ok": True, "staging_gib": round(staging, 1), "headline": head,
            "detail": detail, "note": note, "bd50": bd, "uhd": uhd, "dvd9": dvd}


def size_guide():
    """The recommendation table, computed from the same constants as card_advice.

    Written out rather than hard-coded in the interface so the advice on screen cannot
    drift away from the maths in docs/design/storage-sizing.md.
    """
    rows = []
    for gb in (32, 64, 128, 256):
        a = card_advice(gb * 1_000_000_000)
        rows.append({"label": "%d GB" % gb, "bytes": gb * 1_000_000_000,
                     "staging_gib": a["staging_gib"], "headline": a["headline"],
                     "detail": a["detail"]})
    return rows


def list_disks():
    """External, physical media, classified. The boot drive can never appear.

    Everything that survives is returned -- including things that look like external
    drives, flagged as such. Filtering them out of the *card* list is the interface's
    job (it offers them behind a reveal, the way Rufus does), because a hidden device
    the user is sure they inserted is its own support problem.
    """
    try:
        out = subprocess.run(
            ["diskutil", "list", "-plist", "external", "physical"],
            capture_output=True).stdout
        disks = plistlib.loads(out).get("AllDisksAndPartitions", [])
    except Exception:
        return []
    icons = _media_icons()
    res = []
    for d in disks:
        ident = d.get("DeviceIdentifier")
        if not ident:
            continue
        try:
            info = plistlib.loads(subprocess.run(
                ["diskutil", "info", "-plist", ident], capture_output=True).stdout)
        except Exception:
            continue
        if info.get("VirtualOrPhysical") == "Virtual":
            continue
        if info.get("Internal", False) or info.get("SystemImage", False):
            continue
        # Ejectable *or* removable media still decides whether a device is a candidate
        # at all -- it is only the card-versus-drive question that needs them apart.
        if not info.get("Ejectable", False) and \
                not _truthy_removable(info.get("RemovableMedia")):
            continue
        size = info.get("TotalSize", 0)
        if not (MIN_DISK_BYTES < size < MAX_DISK_BYTES):
            continue
        kind, why = classify_disk(info, icons.get(ident, ""))
        label, is_card, rank = DISK_KINDS[kind]
        res.append({
            "id": ident,
            "size": size,
            "size_gb": round(size / 1e9, 1),
            "name": (info.get("MediaName") or "?").strip(),
            "protocol": info.get("BusProtocol", ""),
            "kind": kind,
            "kind_label": label,
            "is_card": is_card,
            "why": why,
            "advice": card_advice(size),
        })
    res.sort(key=lambda d: (DISK_KINDS[d["kind"]][2], d["id"]))
    return res


def validate_disk(ident, allow_any=False):
    """Re-check a disk immediately before writing. Never trust a cached list.

    `allow_any` is the user having deliberately revealed and chosen something we
    classified as an external drive. Without it, a device that changed classification
    between listing and writing -- or an identifier that arrived from somewhere other
    than the list -- is refused.
    """
    for d in list_disks():
        if d["id"] == ident and (allow_any or d["is_card"]):
            return d
    return None


# ──────────────────────────── Provisioning ────────────────────────────

def sha512_crypt(pw):
    """macOS crypt(3) has no $6$ support and silently returns a DES hash instead.

    crypt.crypt('test', '$6$...') yields '$6asQOJRqB1i2' — a DES hash wearing a
    prefix. That produces a card whose console login cannot work, discoverable only
    after flashing and booting. passlib is a hard requirement for this reason.
    """
    from passlib.hash import sha512_crypt as s
    return s.using(rounds=5000).hash(pw)


def _esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def build_toml(cfg):
    """Generate custom.toml.

    Schema verified against raspberrypi-sys-mods/init_config, not from memory.
    `password_encrypted` defaults to TRUE for both [user] and [wlan], so a plaintext
    value supplied without explicitly setting it false fails in a way that is close to
    undiagnosable on a headless box.
    """
    lines = [
        "# Generated by the Riparr Preparer",
        "# Schema verified against raspberrypi-sys-mods/init_config",
        "config_version = 1",
        "",
        "[system]",
        'hostname = "%s"' % _esc(cfg["hostname"]),
        "",
        "[user]",
        'name = "%s"' % _esc(cfg["user"]),
        'password = "%s"' % cfg["pw_hash"],
        "password_encrypted = true",
        "",
        "[ssh]",
        "enabled = true",
        "password_authentication = true",
    ]
    if cfg.get("authorized_key"):
        lines.append('authorized_keys = [ "%s" ]' % _esc(cfg["authorized_key"]))
    lines += ["", "[wlan]", 'ssid = "%s"' % _esc(cfg["ssid"])]
    if cfg.get("secure"):
        lines += ['password = "%s"' % derive_psk(cfg["ssid"], cfg["wifi_pw"]),
                  "password_encrypted = true"]
    lines += ["hidden = %s" % ("true" if cfg.get("hidden") else "false"),
              'country = "%s"' % _esc(cfg.get("country", "US")),
              "",
              "[locale]",
              'keymap = "%s"' % _esc(cfg.get("keymap", "us")),
              'timezone = "%s"' % _esc(cfg.get("timezone", "UTC")),
              ""]
    return "\n".join(lines)


def host_timezone():
    if os.path.islink("/etc/localtime"):
        return os.readlink("/etc/localtime").split("zoneinfo/")[-1]
    return "UTC"


# ────────────────────────────── Assets ──────────────────────────────

def expected_sha256(image_path):
    """Read the checksum sidecar if there is one.

    Raspberry Pi publishes these and we already download them; not checking meant a
    corrupted image produced a card that failed later, mysteriously, on the Pi.
    Format is `<hex>  <filename>`; the filename inside may differ from ours if the
    image was renamed, so only the hex is used.
    """
    for cand in (image_path + ".sha256", os.path.splitext(image_path)[0] + ".sha256"):
        if os.path.exists(cand):
            try:
                first = open(cand).read().split()
                if first and len(first[0]) == 64:
                    return first[0].lower()
            except OSError:
                pass
    return None


def image_kind(path):
    """Whether this image carries Riparr, or is a stock Raspberry Pi OS image.

    The success screen must not promise a web interface that will not be there. Until a
    Riparr image exists, every card written by this tool boots to stock Raspberry Pi OS
    and is reachable only over SSH.
    """
    name = os.path.basename(path).lower()
    return "riparr" if "riparr" in name else "raspios"


def find_images(assets):
    """Every .img.xz in the assets dir, newest first."""
    try:
        names = [f for f in os.listdir(assets) if f.endswith(".img.xz")]
    except OSError:
        return []
    out = []
    for n in names:
        p = os.path.join(assets, n)
        out.append({"name": n, "path": p,
                    "size": os.path.getsize(p),
                    "mtime": os.path.getmtime(p),
                    "sha256": expected_sha256(p),
                    "kind": image_kind(p)})
    out.sort(key=lambda d: d["mtime"], reverse=True)
    return out


def uncompressed_size(path):
    """Read the real expanded size out of the xz index, for an honest progress bar."""
    try:
        out = subprocess.run(["xz", "--robot", "--list", path],
                             capture_output=True, text=True).stdout
        for line in out.splitlines():
            f = line.split("\t")
            if f[0] == "file":
                return int(f[4])
    except Exception:
        pass
    return 0


def ensure_password(assets):
    """Read the saved account password, generating one on first run."""
    pwfile = os.path.join(assets, "user_password.txt")
    if os.path.exists(pwfile):
        return open(pwfile).read().strip(), False
    pw = "".join(secrets.choice(string.ascii_letters + string.digits)
                 for _ in range(20))
    with open(pwfile, "w") as f:
        f.write(pw + "\n")
    os.chmod(pwfile, 0o600)
    return pw, True


def public_key(assets):
    p = os.path.join(assets, "riparr_key.pub")
    return open(p).read().strip() if os.path.exists(p) else None


# ────────────────────────────── Updates ──────────────────────────────

def check_for_update(current_version, repo=RIPARR_REPO, timeout=6):
    """Ask GitHub for the newest release.

    Returns a dict the UI can render directly. Never raises — a machine with no
    internet must still be able to flash a card.
    """
    url = "%s/repos/%s/releases/latest" % (GITHUB_API, repo)
    req = urllib.request.Request(url, headers={
        "Accept": "application/vnd.github+json",
        "User-Agent": "riparr-preparer/%s" % current_version,
    })
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            data = json.load(r)
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return {"status": "no-releases", "repo": repo}
        return {"status": "error", "detail": "HTTP %s" % e.code}
    except Exception as e:
        return {"status": "offline", "detail": str(e)}

    tag = (data.get("tag_name") or "").lstrip("v")
    assets = [{"name": a.get("name"), "url": a.get("browser_download_url"),
               "size": a.get("size")} for a in data.get("assets", [])]
    return {
        "status": "update" if _newer(tag, current_version) else "current",
        "version": tag,
        "current": current_version,
        "url": data.get("html_url"),
        "notes": data.get("body") or "",
        "published": data.get("published_at"),
        "assets": assets,
        "repo": repo,
    }


def _newer(a, b):
    """Compare dotted versions. Non-numeric segments sort as 0 rather than crashing."""
    def parts(v):
        return [int(x) if x.isdigit() else 0
                for x in re.split(r"[.\-+]", v or "") if x != ""]
    pa, pb = parts(a), parts(b)
    n = max(len(pa), len(pb))
    pa += [0] * (n - len(pa))
    pb += [0] * (n - len(pb))
    return pa > pb
